name: Run Postman Tests

on: [push, pull_request]

jobs:
  postman-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - run: npm install -g newman
      - name: Run Postman Collection
        run: newman run EditProduct.postman_collection.json --iteration-data corrected_product_names.csv